name: tp_sql_ecommerce

services:
  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - v_pgdb:/var/lib/postgresql
      - ./sql_init:/docker-entrypoint-initdb.d
    networks:
      - pgdb_network
      - app_network
    restart: always

  pgadmin:
    depends_on:
      - pgdb
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./.env
    ports:
      - 8080:80
    volumes:
      - v_pgadmin:/var/lib/pgadmin
    networks:
      - pgdb_network
    restart: always

  app:
    depends_on:
      - pgdb
    build: ./app
    container_name: app
    env_file:
      - ./.env
    ports:
      - 5000:5000
    volumes:
      - ~/Documents:/app/reports
    networks:
      - app_network
    restart: always

volumes:
  v_pgdb:
  v_pgadmin:

networks:
  pgdb_network:
  app_network: